from __future__ import annotations

from typing import Protocol

from nexus_memory.domain.models import (
    DIGEST_VERSION,
    HistoryPage,
    RevisionHit,
    MemoryInput,
    MemoryView,
    RepositoryBinding,
    Scope,
    SearchPage,
    SearchQuery,
    StoreStatus,
    VerifiedReference,
    WriteReceipt,
)


class MemoryRepository(Protocol):
    def record(self, scope: Scope, item: MemoryInput, key: str, digest: str,
               references: tuple[VerifiedReference, ...] = (), digest_version: int = DIGEST_VERSION) -> WriteReceipt: ...
    def revise(self, scope: Scope, memory_id: str, expected_revision_id: str, item: MemoryInput, key: str, digest: str,
               references: tuple[VerifiedReference, ...] = (), digest_version: int = DIGEST_VERSION) -> WriteReceipt: ...
    def forget(self, scope: Scope, memory_id: str, expected_revision_id: str, key: str, digest: str) -> WriteReceipt: ...
    def receipt(self, scope: Scope, key: str, digest: str) -> WriteReceipt | None: ...
    def get(self, scope: Scope, memory_id: str, revision_id: str | None = None) -> MemoryView: ...
    def search(self, scope: Scope, query: SearchQuery) -> SearchPage: ...
    def search_history(self, scope: Scope, query: SearchQuery) -> tuple[RevisionHit, ...]: ...
    def history(self, scope: Scope, memory_id: str, limit: int, cursor: str | None = None) -> HistoryPage: ...
    def status(self, scope: Scope) -> StoreStatus: ...
    def bind_checkout(self, scope: Scope, token: str, locator: str | None, object_format: str,
                      repository_id: str | None = None) -> RepositoryBinding: ...
    def checkout_binding(self, scope: Scope, token: str) -> RepositoryBinding | None: ...
