from __future__ import annotations

from typing import Protocol

from nexus_memory.domain.models import MemoryInput, MemoryView, Scope, StoreStatus, WriteReceipt


class MemoryRepository(Protocol):
    def record(self, scope: Scope, item: MemoryInput, key: str, digest: str) -> WriteReceipt: ...
    def revise(self, scope: Scope, memory_id: str, expected_revision_id: str, item: MemoryInput, key: str, digest: str) -> WriteReceipt: ...
    def forget(self, scope: Scope, memory_id: str, expected_revision_id: str, key: str, digest: str) -> WriteReceipt: ...
    def get(self, scope: Scope, memory_id: str, revision_id: str | None = None) -> MemoryView: ...
    def status(self, scope: Scope) -> StoreStatus: ...
